router id 192.168.1.254;

debug protocols all;

log "bird.log" all;

protocol kernel {
    learn;
    scan time 10;
    ipv4 {
        import filter {
            if (net ~ [192.0.0.0/8+]) then accept;
            reject;
        };
        # export filter {
        #     if (net ~ [192.0.0.0/8+]) then accept;
        #     reject;
        # };
    };
}

# protocol direct {
#     ipv4 {
#         import filter {
#             if (net ~ [192.168.0.0/16+]) then reject;
#             accept;
#         };
#     };
#     interface "gretun";
# }

protocol device {
    scan time 10;
}

protocol static {
    ipv4;
    include "node1_IPswen_level0_1000000.conf";
#    route 111.10.0.0(1)128/33 via 10.10.10.1;
#    route 222.10.0.0(-1)128/33 via 10.10.10.1;
#    route 100.10.0.0(-2)128.128/41 via 10.10.10.1;
#    route 200.10.0.0/24 via 10.10.10.1;

}

protocol bgp {
    neighbor fc70::1 as 65151;
    local fc70::2 port 1109 as 65150;
    graceful restart;
    multihop;
    extended next hop;
    keepalive time 30;
    ipv4 {
        import filter {
            if (net ~ [192.168.0.0/16+]) then reject;
            accept;
        };
        export filter {
            if (net ~ [192.168.0.0/16+]) then reject;
            accept;
        };
        next hop self;
    };
}

# protocol bgp {
#     neighbor 192.168.2.1 as 65151;
#     local 192.168.2.2 as 65152;
#     graceful restart;
#     multihop;
#     keepalive time 30;
#     ipv4 {
#         import filter {
#             if (net ~ [192.168.0.0/16+]) then reject;
#             accept;
#         };
#         export filter {
#             if (net ~ [192.168.0.0/16+]) then reject;
#             accept;
#         };
#         next hop self;
#     };
# }
