log "bird.log" all;
router id 192.168.1.254;
protocol static {
    ipswen;
    route 1.0.0.0(2)0.0/40 blackhole;
    route 1.0.0.0(2)1.0/40 blackhole;
    route 1.0.0.0(2)2.0/40 blackhole;
    route 1.0.0.0(2)3.0/40 blackhole;
    route 1.0.0.0(2)4.0/40 blackhole;
    route 1.0.0.0(2)5.0/40 blackhole;
}

protocol bgp {
    neighbor 192.168.1.255 as 65151;
    local 192.168.1.254 port 1109 as 65150;
    multihop;
    keepalive time 30;
    ipv4 {
        import filter {
            if (net ~ [192.168.0.0/16+]) then reject;
            accept;
        };
        export filter {
            if (net ~ [192.168.0.0/16+]) then reject;
            accept;
        };
        next hop self;
    };
}
